// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: itemInfo.proto

#ifndef PROTOBUF_itemInfo_2eproto__INCLUDED
#define PROTOBUF_itemInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_itemInfo_2eproto();
void protobuf_AssignDesc_itemInfo_2eproto();
void protobuf_ShutdownFile_itemInfo_2eproto();

class itemInfo;
class itemInfo_t_itemInfo;

// ===================================================================

class itemInfo_t_itemInfo : public ::google::protobuf::Message {
 public:
  itemInfo_t_itemInfo();
  virtual ~itemInfo_t_itemInfo();

  itemInfo_t_itemInfo(const itemInfo_t_itemInfo& from);

  inline itemInfo_t_itemInfo& operator=(const itemInfo_t_itemInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const itemInfo_t_itemInfo& default_instance();

  void Swap(itemInfo_t_itemInfo* other);

  // implements Message ----------------------------------------------

  itemInfo_t_itemInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const itemInfo_t_itemInfo& from);
  void MergeFrom(const itemInfo_t_itemInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 tbxid = 1;
  inline bool has_tbxid() const;
  inline void clear_tbxid();
  static const int kTbxidFieldNumber = 1;
  inline ::google::protobuf::uint32 tbxid() const;
  inline void set_tbxid(::google::protobuf::uint32 value);

  // required uint32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required string item = 3;
  inline bool has_item() const;
  inline void clear_item();
  static const int kItemFieldNumber = 3;
  inline const ::std::string& item() const;
  inline void set_item(const ::std::string& value);
  inline void set_item(const char* value);
  inline void set_item(const char* value, size_t size);
  inline ::std::string* mutable_item();
  inline ::std::string* release_item();
  inline void set_allocated_item(::std::string* item);

  // required uint32 level = 4;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 4;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);

  // required uint32 getWay = 5;
  inline bool has_getway() const;
  inline void clear_getway();
  static const int kGetWayFieldNumber = 5;
  inline ::google::protobuf::uint32 getway() const;
  inline void set_getway(::google::protobuf::uint32 value);

  // required uint32 function = 6;
  inline bool has_function() const;
  inline void clear_function();
  static const int kFunctionFieldNumber = 6;
  inline ::google::protobuf::uint32 function() const;
  inline void set_function(::google::protobuf::uint32 value);

  // required uint32 grade = 7;
  inline bool has_grade() const;
  inline void clear_grade();
  static const int kGradeFieldNumber = 7;
  inline ::google::protobuf::uint32 grade() const;
  inline void set_grade(::google::protobuf::uint32 value);

  // required uint32 price = 8;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 8;
  inline ::google::protobuf::uint32 price() const;
  inline void set_price(::google::protobuf::uint32 value);

  // required uint32 part = 9;
  inline bool has_part() const;
  inline void clear_part();
  static const int kPartFieldNumber = 9;
  inline ::google::protobuf::uint32 part() const;
  inline void set_part(::google::protobuf::uint32 value);

  // required uint32 kind = 10;
  inline bool has_kind() const;
  inline void clear_kind();
  static const int kKindFieldNumber = 10;
  inline ::google::protobuf::uint32 kind() const;
  inline void set_kind(::google::protobuf::uint32 value);

  // required uint32 tier = 11;
  inline bool has_tier() const;
  inline void clear_tier();
  static const int kTierFieldNumber = 11;
  inline ::google::protobuf::uint32 tier() const;
  inline void set_tier(::google::protobuf::uint32 value);

  // required uint32 tierFunction1 = 12;
  inline bool has_tierfunction1() const;
  inline void clear_tierfunction1();
  static const int kTierFunction1FieldNumber = 12;
  inline ::google::protobuf::uint32 tierfunction1() const;
  inline void set_tierfunction1(::google::protobuf::uint32 value);

  // required uint32 tierAttribute1 = 13;
  inline bool has_tierattribute1() const;
  inline void clear_tierattribute1();
  static const int kTierAttribute1FieldNumber = 13;
  inline ::google::protobuf::uint32 tierattribute1() const;
  inline void set_tierattribute1(::google::protobuf::uint32 value);

  // required uint32 tierFunction2 = 14;
  inline bool has_tierfunction2() const;
  inline void clear_tierfunction2();
  static const int kTierFunction2FieldNumber = 14;
  inline ::google::protobuf::uint32 tierfunction2() const;
  inline void set_tierfunction2(::google::protobuf::uint32 value);

  // required uint32 tierAttribute2 = 15;
  inline bool has_tierattribute2() const;
  inline void clear_tierattribute2();
  static const int kTierAttribute2FieldNumber = 15;
  inline ::google::protobuf::uint32 tierattribute2() const;
  inline void set_tierattribute2(::google::protobuf::uint32 value);

  // required uint32 tierFunction3 = 16;
  inline bool has_tierfunction3() const;
  inline void clear_tierfunction3();
  static const int kTierFunction3FieldNumber = 16;
  inline ::google::protobuf::uint32 tierfunction3() const;
  inline void set_tierfunction3(::google::protobuf::uint32 value);

  // required uint32 tierAttribute3 = 17;
  inline bool has_tierattribute3() const;
  inline void clear_tierattribute3();
  static const int kTierAttribute3FieldNumber = 17;
  inline ::google::protobuf::uint32 tierattribute3() const;
  inline void set_tierattribute3(::google::protobuf::uint32 value);

  // required uint32 card = 18;
  inline bool has_card() const;
  inline void clear_card();
  static const int kCardFieldNumber = 18;
  inline ::google::protobuf::uint32 card() const;
  inline void set_card(::google::protobuf::uint32 value);

  // required string describe = 19;
  inline bool has_describe() const;
  inline void clear_describe();
  static const int kDescribeFieldNumber = 19;
  inline const ::std::string& describe() const;
  inline void set_describe(const ::std::string& value);
  inline void set_describe(const char* value);
  inline void set_describe(const char* value, size_t size);
  inline ::std::string* mutable_describe();
  inline ::std::string* release_describe();
  inline void set_allocated_describe(::std::string* describe);

  // @@protoc_insertion_point(class_scope:pb.itemInfo.t_itemInfo)
 private:
  inline void set_has_tbxid();
  inline void clear_has_tbxid();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_item();
  inline void clear_has_item();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_getway();
  inline void clear_has_getway();
  inline void set_has_function();
  inline void clear_has_function();
  inline void set_has_grade();
  inline void clear_has_grade();
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_part();
  inline void clear_has_part();
  inline void set_has_kind();
  inline void clear_has_kind();
  inline void set_has_tier();
  inline void clear_has_tier();
  inline void set_has_tierfunction1();
  inline void clear_has_tierfunction1();
  inline void set_has_tierattribute1();
  inline void clear_has_tierattribute1();
  inline void set_has_tierfunction2();
  inline void clear_has_tierfunction2();
  inline void set_has_tierattribute2();
  inline void clear_has_tierattribute2();
  inline void set_has_tierfunction3();
  inline void clear_has_tierfunction3();
  inline void set_has_tierattribute3();
  inline void clear_has_tierattribute3();
  inline void set_has_card();
  inline void clear_has_card();
  inline void set_has_describe();
  inline void clear_has_describe();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 tbxid_;
  ::google::protobuf::uint32 id_;
  ::std::string* item_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 getway_;
  ::google::protobuf::uint32 function_;
  ::google::protobuf::uint32 grade_;
  ::google::protobuf::uint32 price_;
  ::google::protobuf::uint32 part_;
  ::google::protobuf::uint32 kind_;
  ::google::protobuf::uint32 tier_;
  ::google::protobuf::uint32 tierfunction1_;
  ::google::protobuf::uint32 tierattribute1_;
  ::google::protobuf::uint32 tierfunction2_;
  ::google::protobuf::uint32 tierattribute2_;
  ::google::protobuf::uint32 tierfunction3_;
  ::google::protobuf::uint32 tierattribute3_;
  ::std::string* describe_;
  ::google::protobuf::uint32 card_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(19 + 31) / 32];

  friend void  protobuf_AddDesc_itemInfo_2eproto();
  friend void protobuf_AssignDesc_itemInfo_2eproto();
  friend void protobuf_ShutdownFile_itemInfo_2eproto();

  void InitAsDefaultInstance();
  static itemInfo_t_itemInfo* default_instance_;
};
// -------------------------------------------------------------------

class itemInfo : public ::google::protobuf::Message {
 public:
  itemInfo();
  virtual ~itemInfo();

  itemInfo(const itemInfo& from);

  inline itemInfo& operator=(const itemInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const itemInfo& default_instance();

  void Swap(itemInfo* other);

  // implements Message ----------------------------------------------

  itemInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const itemInfo& from);
  void MergeFrom(const itemInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef itemInfo_t_itemInfo t_itemInfo;

  // accessors -------------------------------------------------------

  // repeated .pb.itemInfo.t_itemInfo datas = 1;
  inline int datas_size() const;
  inline void clear_datas();
  static const int kDatasFieldNumber = 1;
  inline const ::pb::itemInfo_t_itemInfo& datas(int index) const;
  inline ::pb::itemInfo_t_itemInfo* mutable_datas(int index);
  inline ::pb::itemInfo_t_itemInfo* add_datas();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::itemInfo_t_itemInfo >&
      datas() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::itemInfo_t_itemInfo >*
      mutable_datas();

  // @@protoc_insertion_point(class_scope:pb.itemInfo)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::pb::itemInfo_t_itemInfo > datas_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_itemInfo_2eproto();
  friend void protobuf_AssignDesc_itemInfo_2eproto();
  friend void protobuf_ShutdownFile_itemInfo_2eproto();

  void InitAsDefaultInstance();
  static itemInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// itemInfo_t_itemInfo

// required uint32 tbxid = 1;
inline bool itemInfo_t_itemInfo::has_tbxid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_tbxid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void itemInfo_t_itemInfo::clear_has_tbxid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void itemInfo_t_itemInfo::clear_tbxid() {
  tbxid_ = 0u;
  clear_has_tbxid();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::tbxid() const {
  return tbxid_;
}
inline void itemInfo_t_itemInfo::set_tbxid(::google::protobuf::uint32 value) {
  set_has_tbxid();
  tbxid_ = value;
}

// required uint32 id = 2;
inline bool itemInfo_t_itemInfo::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void itemInfo_t_itemInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void itemInfo_t_itemInfo::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::id() const {
  return id_;
}
inline void itemInfo_t_itemInfo::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required string item = 3;
inline bool itemInfo_t_itemInfo::has_item() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_item() {
  _has_bits_[0] |= 0x00000004u;
}
inline void itemInfo_t_itemInfo::clear_has_item() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void itemInfo_t_itemInfo::clear_item() {
  if (item_ != &::google::protobuf::internal::kEmptyString) {
    item_->clear();
  }
  clear_has_item();
}
inline const ::std::string& itemInfo_t_itemInfo::item() const {
  return *item_;
}
inline void itemInfo_t_itemInfo::set_item(const ::std::string& value) {
  set_has_item();
  if (item_ == &::google::protobuf::internal::kEmptyString) {
    item_ = new ::std::string;
  }
  item_->assign(value);
}
inline void itemInfo_t_itemInfo::set_item(const char* value) {
  set_has_item();
  if (item_ == &::google::protobuf::internal::kEmptyString) {
    item_ = new ::std::string;
  }
  item_->assign(value);
}
inline void itemInfo_t_itemInfo::set_item(const char* value, size_t size) {
  set_has_item();
  if (item_ == &::google::protobuf::internal::kEmptyString) {
    item_ = new ::std::string;
  }
  item_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* itemInfo_t_itemInfo::mutable_item() {
  set_has_item();
  if (item_ == &::google::protobuf::internal::kEmptyString) {
    item_ = new ::std::string;
  }
  return item_;
}
inline ::std::string* itemInfo_t_itemInfo::release_item() {
  clear_has_item();
  if (item_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = item_;
    item_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void itemInfo_t_itemInfo::set_allocated_item(::std::string* item) {
  if (item_ != &::google::protobuf::internal::kEmptyString) {
    delete item_;
  }
  if (item) {
    set_has_item();
    item_ = item;
  } else {
    clear_has_item();
    item_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 level = 4;
inline bool itemInfo_t_itemInfo::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void itemInfo_t_itemInfo::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void itemInfo_t_itemInfo::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::level() const {
  return level_;
}
inline void itemInfo_t_itemInfo::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
}

// required uint32 getWay = 5;
inline bool itemInfo_t_itemInfo::has_getway() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_getway() {
  _has_bits_[0] |= 0x00000010u;
}
inline void itemInfo_t_itemInfo::clear_has_getway() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void itemInfo_t_itemInfo::clear_getway() {
  getway_ = 0u;
  clear_has_getway();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::getway() const {
  return getway_;
}
inline void itemInfo_t_itemInfo::set_getway(::google::protobuf::uint32 value) {
  set_has_getway();
  getway_ = value;
}

// required uint32 function = 6;
inline bool itemInfo_t_itemInfo::has_function() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_function() {
  _has_bits_[0] |= 0x00000020u;
}
inline void itemInfo_t_itemInfo::clear_has_function() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void itemInfo_t_itemInfo::clear_function() {
  function_ = 0u;
  clear_has_function();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::function() const {
  return function_;
}
inline void itemInfo_t_itemInfo::set_function(::google::protobuf::uint32 value) {
  set_has_function();
  function_ = value;
}

// required uint32 grade = 7;
inline bool itemInfo_t_itemInfo::has_grade() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_grade() {
  _has_bits_[0] |= 0x00000040u;
}
inline void itemInfo_t_itemInfo::clear_has_grade() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void itemInfo_t_itemInfo::clear_grade() {
  grade_ = 0u;
  clear_has_grade();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::grade() const {
  return grade_;
}
inline void itemInfo_t_itemInfo::set_grade(::google::protobuf::uint32 value) {
  set_has_grade();
  grade_ = value;
}

// required uint32 price = 8;
inline bool itemInfo_t_itemInfo::has_price() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_price() {
  _has_bits_[0] |= 0x00000080u;
}
inline void itemInfo_t_itemInfo::clear_has_price() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void itemInfo_t_itemInfo::clear_price() {
  price_ = 0u;
  clear_has_price();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::price() const {
  return price_;
}
inline void itemInfo_t_itemInfo::set_price(::google::protobuf::uint32 value) {
  set_has_price();
  price_ = value;
}

// required uint32 part = 9;
inline bool itemInfo_t_itemInfo::has_part() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_part() {
  _has_bits_[0] |= 0x00000100u;
}
inline void itemInfo_t_itemInfo::clear_has_part() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void itemInfo_t_itemInfo::clear_part() {
  part_ = 0u;
  clear_has_part();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::part() const {
  return part_;
}
inline void itemInfo_t_itemInfo::set_part(::google::protobuf::uint32 value) {
  set_has_part();
  part_ = value;
}

// required uint32 kind = 10;
inline bool itemInfo_t_itemInfo::has_kind() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_kind() {
  _has_bits_[0] |= 0x00000200u;
}
inline void itemInfo_t_itemInfo::clear_has_kind() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void itemInfo_t_itemInfo::clear_kind() {
  kind_ = 0u;
  clear_has_kind();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::kind() const {
  return kind_;
}
inline void itemInfo_t_itemInfo::set_kind(::google::protobuf::uint32 value) {
  set_has_kind();
  kind_ = value;
}

// required uint32 tier = 11;
inline bool itemInfo_t_itemInfo::has_tier() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_tier() {
  _has_bits_[0] |= 0x00000400u;
}
inline void itemInfo_t_itemInfo::clear_has_tier() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void itemInfo_t_itemInfo::clear_tier() {
  tier_ = 0u;
  clear_has_tier();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::tier() const {
  return tier_;
}
inline void itemInfo_t_itemInfo::set_tier(::google::protobuf::uint32 value) {
  set_has_tier();
  tier_ = value;
}

// required uint32 tierFunction1 = 12;
inline bool itemInfo_t_itemInfo::has_tierfunction1() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_tierfunction1() {
  _has_bits_[0] |= 0x00000800u;
}
inline void itemInfo_t_itemInfo::clear_has_tierfunction1() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void itemInfo_t_itemInfo::clear_tierfunction1() {
  tierfunction1_ = 0u;
  clear_has_tierfunction1();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::tierfunction1() const {
  return tierfunction1_;
}
inline void itemInfo_t_itemInfo::set_tierfunction1(::google::protobuf::uint32 value) {
  set_has_tierfunction1();
  tierfunction1_ = value;
}

// required uint32 tierAttribute1 = 13;
inline bool itemInfo_t_itemInfo::has_tierattribute1() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_tierattribute1() {
  _has_bits_[0] |= 0x00001000u;
}
inline void itemInfo_t_itemInfo::clear_has_tierattribute1() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void itemInfo_t_itemInfo::clear_tierattribute1() {
  tierattribute1_ = 0u;
  clear_has_tierattribute1();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::tierattribute1() const {
  return tierattribute1_;
}
inline void itemInfo_t_itemInfo::set_tierattribute1(::google::protobuf::uint32 value) {
  set_has_tierattribute1();
  tierattribute1_ = value;
}

// required uint32 tierFunction2 = 14;
inline bool itemInfo_t_itemInfo::has_tierfunction2() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_tierfunction2() {
  _has_bits_[0] |= 0x00002000u;
}
inline void itemInfo_t_itemInfo::clear_has_tierfunction2() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void itemInfo_t_itemInfo::clear_tierfunction2() {
  tierfunction2_ = 0u;
  clear_has_tierfunction2();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::tierfunction2() const {
  return tierfunction2_;
}
inline void itemInfo_t_itemInfo::set_tierfunction2(::google::protobuf::uint32 value) {
  set_has_tierfunction2();
  tierfunction2_ = value;
}

// required uint32 tierAttribute2 = 15;
inline bool itemInfo_t_itemInfo::has_tierattribute2() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_tierattribute2() {
  _has_bits_[0] |= 0x00004000u;
}
inline void itemInfo_t_itemInfo::clear_has_tierattribute2() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void itemInfo_t_itemInfo::clear_tierattribute2() {
  tierattribute2_ = 0u;
  clear_has_tierattribute2();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::tierattribute2() const {
  return tierattribute2_;
}
inline void itemInfo_t_itemInfo::set_tierattribute2(::google::protobuf::uint32 value) {
  set_has_tierattribute2();
  tierattribute2_ = value;
}

// required uint32 tierFunction3 = 16;
inline bool itemInfo_t_itemInfo::has_tierfunction3() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_tierfunction3() {
  _has_bits_[0] |= 0x00008000u;
}
inline void itemInfo_t_itemInfo::clear_has_tierfunction3() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void itemInfo_t_itemInfo::clear_tierfunction3() {
  tierfunction3_ = 0u;
  clear_has_tierfunction3();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::tierfunction3() const {
  return tierfunction3_;
}
inline void itemInfo_t_itemInfo::set_tierfunction3(::google::protobuf::uint32 value) {
  set_has_tierfunction3();
  tierfunction3_ = value;
}

// required uint32 tierAttribute3 = 17;
inline bool itemInfo_t_itemInfo::has_tierattribute3() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_tierattribute3() {
  _has_bits_[0] |= 0x00010000u;
}
inline void itemInfo_t_itemInfo::clear_has_tierattribute3() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void itemInfo_t_itemInfo::clear_tierattribute3() {
  tierattribute3_ = 0u;
  clear_has_tierattribute3();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::tierattribute3() const {
  return tierattribute3_;
}
inline void itemInfo_t_itemInfo::set_tierattribute3(::google::protobuf::uint32 value) {
  set_has_tierattribute3();
  tierattribute3_ = value;
}

// required uint32 card = 18;
inline bool itemInfo_t_itemInfo::has_card() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_card() {
  _has_bits_[0] |= 0x00020000u;
}
inline void itemInfo_t_itemInfo::clear_has_card() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void itemInfo_t_itemInfo::clear_card() {
  card_ = 0u;
  clear_has_card();
}
inline ::google::protobuf::uint32 itemInfo_t_itemInfo::card() const {
  return card_;
}
inline void itemInfo_t_itemInfo::set_card(::google::protobuf::uint32 value) {
  set_has_card();
  card_ = value;
}

// required string describe = 19;
inline bool itemInfo_t_itemInfo::has_describe() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void itemInfo_t_itemInfo::set_has_describe() {
  _has_bits_[0] |= 0x00040000u;
}
inline void itemInfo_t_itemInfo::clear_has_describe() {
  _has_bits_[0] &= ~0x00040000u;
}
inline void itemInfo_t_itemInfo::clear_describe() {
  if (describe_ != &::google::protobuf::internal::kEmptyString) {
    describe_->clear();
  }
  clear_has_describe();
}
inline const ::std::string& itemInfo_t_itemInfo::describe() const {
  return *describe_;
}
inline void itemInfo_t_itemInfo::set_describe(const ::std::string& value) {
  set_has_describe();
  if (describe_ == &::google::protobuf::internal::kEmptyString) {
    describe_ = new ::std::string;
  }
  describe_->assign(value);
}
inline void itemInfo_t_itemInfo::set_describe(const char* value) {
  set_has_describe();
  if (describe_ == &::google::protobuf::internal::kEmptyString) {
    describe_ = new ::std::string;
  }
  describe_->assign(value);
}
inline void itemInfo_t_itemInfo::set_describe(const char* value, size_t size) {
  set_has_describe();
  if (describe_ == &::google::protobuf::internal::kEmptyString) {
    describe_ = new ::std::string;
  }
  describe_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* itemInfo_t_itemInfo::mutable_describe() {
  set_has_describe();
  if (describe_ == &::google::protobuf::internal::kEmptyString) {
    describe_ = new ::std::string;
  }
  return describe_;
}
inline ::std::string* itemInfo_t_itemInfo::release_describe() {
  clear_has_describe();
  if (describe_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = describe_;
    describe_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void itemInfo_t_itemInfo::set_allocated_describe(::std::string* describe) {
  if (describe_ != &::google::protobuf::internal::kEmptyString) {
    delete describe_;
  }
  if (describe) {
    set_has_describe();
    describe_ = describe;
  } else {
    clear_has_describe();
    describe_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// itemInfo

// repeated .pb.itemInfo.t_itemInfo datas = 1;
inline int itemInfo::datas_size() const {
  return datas_.size();
}
inline void itemInfo::clear_datas() {
  datas_.Clear();
}
inline const ::pb::itemInfo_t_itemInfo& itemInfo::datas(int index) const {
  return datas_.Get(index);
}
inline ::pb::itemInfo_t_itemInfo* itemInfo::mutable_datas(int index) {
  return datas_.Mutable(index);
}
inline ::pb::itemInfo_t_itemInfo* itemInfo::add_datas() {
  return datas_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::itemInfo_t_itemInfo >&
itemInfo::datas() const {
  return datas_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::itemInfo_t_itemInfo >*
itemInfo::mutable_datas() {
  return &datas_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_itemInfo_2eproto__INCLUDED
