// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BurstEventNpc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "BurstEventNpc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {

namespace {

const ::google::protobuf::Descriptor* BurstEventNpc_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BurstEventNpc_reflection_ = NULL;
const ::google::protobuf::Descriptor* BurstEventNpc_t_BurstEventNpc_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BurstEventNpc_t_BurstEventNpc_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_BurstEventNpc_2eproto() {
  protobuf_AddDesc_BurstEventNpc_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "BurstEventNpc.proto");
  GOOGLE_CHECK(file != NULL);
  BurstEventNpc_descriptor_ = file->message_type(0);
  static const int BurstEventNpc_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc, datas_),
  };
  BurstEventNpc_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BurstEventNpc_descriptor_,
      BurstEventNpc::default_instance_,
      BurstEventNpc_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BurstEventNpc));
  BurstEventNpc_t_BurstEventNpc_descriptor_ = BurstEventNpc_descriptor_->nested_type(0);
  static const int BurstEventNpc_t_BurstEventNpc_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc_t_BurstEventNpc, tbxid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc_t_BurstEventNpc, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc_t_BurstEventNpc, npcid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc_t_BurstEventNpc, levelgrade_),
  };
  BurstEventNpc_t_BurstEventNpc_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BurstEventNpc_t_BurstEventNpc_descriptor_,
      BurstEventNpc_t_BurstEventNpc::default_instance_,
      BurstEventNpc_t_BurstEventNpc_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc_t_BurstEventNpc, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BurstEventNpc_t_BurstEventNpc, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BurstEventNpc_t_BurstEventNpc));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_BurstEventNpc_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BurstEventNpc_descriptor_, &BurstEventNpc::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BurstEventNpc_t_BurstEventNpc_descriptor_, &BurstEventNpc_t_BurstEventNpc::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_BurstEventNpc_2eproto() {
  delete BurstEventNpc::default_instance_;
  delete BurstEventNpc_reflection_;
  delete BurstEventNpc_t_BurstEventNpc::default_instance_;
  delete BurstEventNpc_t_BurstEventNpc_reflection_;
}

void protobuf_AddDesc_BurstEventNpc_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023BurstEventNpc.proto\022\002pb\"\222\001\n\rBurstEvent"
    "Npc\0220\n\005datas\030\001 \003(\0132!.pb.BurstEventNpc.t_"
    "BurstEventNpc\032O\n\017t_BurstEventNpc\022\r\n\005tbxi"
    "d\030\001 \002(\r\022\n\n\002id\030\002 \002(\r\022\r\n\005npcid\030\003 \002(\r\022\022\n\nle"
    "velgrade\030\004 \002(\r", 174);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "BurstEventNpc.proto", &protobuf_RegisterTypes);
  BurstEventNpc::default_instance_ = new BurstEventNpc();
  BurstEventNpc_t_BurstEventNpc::default_instance_ = new BurstEventNpc_t_BurstEventNpc();
  BurstEventNpc::default_instance_->InitAsDefaultInstance();
  BurstEventNpc_t_BurstEventNpc::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_BurstEventNpc_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_BurstEventNpc_2eproto {
  StaticDescriptorInitializer_BurstEventNpc_2eproto() {
    protobuf_AddDesc_BurstEventNpc_2eproto();
  }
} static_descriptor_initializer_BurstEventNpc_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int BurstEventNpc_t_BurstEventNpc::kTbxidFieldNumber;
const int BurstEventNpc_t_BurstEventNpc::kIdFieldNumber;
const int BurstEventNpc_t_BurstEventNpc::kNpcidFieldNumber;
const int BurstEventNpc_t_BurstEventNpc::kLevelgradeFieldNumber;
#endif  // !_MSC_VER

BurstEventNpc_t_BurstEventNpc::BurstEventNpc_t_BurstEventNpc()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void BurstEventNpc_t_BurstEventNpc::InitAsDefaultInstance() {
}

BurstEventNpc_t_BurstEventNpc::BurstEventNpc_t_BurstEventNpc(const BurstEventNpc_t_BurstEventNpc& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void BurstEventNpc_t_BurstEventNpc::SharedCtor() {
  _cached_size_ = 0;
  tbxid_ = 0u;
  id_ = 0u;
  npcid_ = 0u;
  levelgrade_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BurstEventNpc_t_BurstEventNpc::~BurstEventNpc_t_BurstEventNpc() {
  SharedDtor();
}

void BurstEventNpc_t_BurstEventNpc::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BurstEventNpc_t_BurstEventNpc::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BurstEventNpc_t_BurstEventNpc::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BurstEventNpc_t_BurstEventNpc_descriptor_;
}

const BurstEventNpc_t_BurstEventNpc& BurstEventNpc_t_BurstEventNpc::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_BurstEventNpc_2eproto();
  return *default_instance_;
}

BurstEventNpc_t_BurstEventNpc* BurstEventNpc_t_BurstEventNpc::default_instance_ = NULL;

BurstEventNpc_t_BurstEventNpc* BurstEventNpc_t_BurstEventNpc::New() const {
  return new BurstEventNpc_t_BurstEventNpc;
}

void BurstEventNpc_t_BurstEventNpc::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    tbxid_ = 0u;
    id_ = 0u;
    npcid_ = 0u;
    levelgrade_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BurstEventNpc_t_BurstEventNpc::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 tbxid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &tbxid_)));
          set_has_tbxid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_id;
        break;
      }

      // required uint32 id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_npcid;
        break;
      }

      // required uint32 npcid = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_npcid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &npcid_)));
          set_has_npcid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_levelgrade;
        break;
      }

      // required uint32 levelgrade = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_levelgrade:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &levelgrade_)));
          set_has_levelgrade();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BurstEventNpc_t_BurstEventNpc::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 tbxid = 1;
  if (has_tbxid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->tbxid(), output);
  }

  // required uint32 id = 2;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->id(), output);
  }

  // required uint32 npcid = 3;
  if (has_npcid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->npcid(), output);
  }

  // required uint32 levelgrade = 4;
  if (has_levelgrade()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->levelgrade(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* BurstEventNpc_t_BurstEventNpc::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 tbxid = 1;
  if (has_tbxid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->tbxid(), target);
  }

  // required uint32 id = 2;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->id(), target);
  }

  // required uint32 npcid = 3;
  if (has_npcid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->npcid(), target);
  }

  // required uint32 levelgrade = 4;
  if (has_levelgrade()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->levelgrade(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int BurstEventNpc_t_BurstEventNpc::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 tbxid = 1;
    if (has_tbxid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->tbxid());
    }

    // required uint32 id = 2;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required uint32 npcid = 3;
    if (has_npcid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->npcid());
    }

    // required uint32 levelgrade = 4;
    if (has_levelgrade()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->levelgrade());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BurstEventNpc_t_BurstEventNpc::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BurstEventNpc_t_BurstEventNpc* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BurstEventNpc_t_BurstEventNpc*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BurstEventNpc_t_BurstEventNpc::MergeFrom(const BurstEventNpc_t_BurstEventNpc& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_tbxid()) {
      set_tbxid(from.tbxid());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_npcid()) {
      set_npcid(from.npcid());
    }
    if (from.has_levelgrade()) {
      set_levelgrade(from.levelgrade());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BurstEventNpc_t_BurstEventNpc::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BurstEventNpc_t_BurstEventNpc::CopyFrom(const BurstEventNpc_t_BurstEventNpc& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BurstEventNpc_t_BurstEventNpc::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void BurstEventNpc_t_BurstEventNpc::Swap(BurstEventNpc_t_BurstEventNpc* other) {
  if (other != this) {
    std::swap(tbxid_, other->tbxid_);
    std::swap(id_, other->id_);
    std::swap(npcid_, other->npcid_);
    std::swap(levelgrade_, other->levelgrade_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BurstEventNpc_t_BurstEventNpc::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BurstEventNpc_t_BurstEventNpc_descriptor_;
  metadata.reflection = BurstEventNpc_t_BurstEventNpc_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BurstEventNpc::kDatasFieldNumber;
#endif  // !_MSC_VER

BurstEventNpc::BurstEventNpc()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void BurstEventNpc::InitAsDefaultInstance() {
}

BurstEventNpc::BurstEventNpc(const BurstEventNpc& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void BurstEventNpc::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BurstEventNpc::~BurstEventNpc() {
  SharedDtor();
}

void BurstEventNpc::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BurstEventNpc::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BurstEventNpc::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BurstEventNpc_descriptor_;
}

const BurstEventNpc& BurstEventNpc::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_BurstEventNpc_2eproto();
  return *default_instance_;
}

BurstEventNpc* BurstEventNpc::default_instance_ = NULL;

BurstEventNpc* BurstEventNpc::New() const {
  return new BurstEventNpc;
}

void BurstEventNpc::Clear() {
  datas_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BurstEventNpc::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.BurstEventNpc.t_BurstEventNpc datas = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_datas:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_datas()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_datas;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BurstEventNpc::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .pb.BurstEventNpc.t_BurstEventNpc datas = 1;
  for (int i = 0; i < this->datas_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->datas(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* BurstEventNpc::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .pb.BurstEventNpc.t_BurstEventNpc datas = 1;
  for (int i = 0; i < this->datas_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->datas(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int BurstEventNpc::ByteSize() const {
  int total_size = 0;

  // repeated .pb.BurstEventNpc.t_BurstEventNpc datas = 1;
  total_size += 1 * this->datas_size();
  for (int i = 0; i < this->datas_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->datas(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BurstEventNpc::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BurstEventNpc* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BurstEventNpc*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BurstEventNpc::MergeFrom(const BurstEventNpc& from) {
  GOOGLE_CHECK_NE(&from, this);
  datas_.MergeFrom(from.datas_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BurstEventNpc::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BurstEventNpc::CopyFrom(const BurstEventNpc& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BurstEventNpc::IsInitialized() const {

  for (int i = 0; i < datas_size(); i++) {
    if (!this->datas(i).IsInitialized()) return false;
  }
  return true;
}

void BurstEventNpc::Swap(BurstEventNpc* other) {
  if (other != this) {
    datas_.Swap(&other->datas_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BurstEventNpc::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BurstEventNpc_descriptor_;
  metadata.reflection = BurstEventNpc_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
