# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Localization.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Localization.proto',
  package='pb',
  serialized_pb='\n\x12Localization.proto\x12\x02pb\"\x9f\x01\n\x0cLocalization\x12.\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\x1f.pb.Localization.t_Localization\x1a_\n\x0et_Localization\x12\r\n\x05tbxid\x18\x01 \x02(\r\x12\n\n\x02id\x18\x02 \x02(\t\x12\x0f\n\x07\x45nglish\x18\x03 \x02(\t\x12\x0f\n\x07\x43hinese\x18\x04 \x02(\t\x12\x10\n\x08Japanese\x18\x05 \x02(\t')




_LOCALIZATION_T_LOCALIZATION = _descriptor.Descriptor(
  name='t_Localization',
  full_name='pb.Localization.t_Localization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tbxid', full_name='pb.Localization.t_Localization.tbxid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.Localization.t_Localization.id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='English', full_name='pb.Localization.t_Localization.English', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Chinese', full_name='pb.Localization.t_Localization.Chinese', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Japanese', full_name='pb.Localization.t_Localization.Japanese', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=91,
  serialized_end=186,
)

_LOCALIZATION = _descriptor.Descriptor(
  name='Localization',
  full_name='pb.Localization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datas', full_name='pb.Localization.datas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LOCALIZATION_T_LOCALIZATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=186,
)

_LOCALIZATION_T_LOCALIZATION.containing_type = _LOCALIZATION;
_LOCALIZATION.fields_by_name['datas'].message_type = _LOCALIZATION_T_LOCALIZATION
DESCRIPTOR.message_types_by_name['Localization'] = _LOCALIZATION

class Localization(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class t_Localization(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LOCALIZATION_T_LOCALIZATION

    # @@protoc_insertion_point(class_scope:pb.Localization.t_Localization)
  DESCRIPTOR = _LOCALIZATION

  # @@protoc_insertion_point(class_scope:pb.Localization)


# @@protoc_insertion_point(module_scope)
